networks:
  loki:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3040:3040
    restart: always
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - loki

  loki:
    image: grafana/loki:2.7.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.7.1
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
      - ./logs:/app/logs
    command: -config.file=/etc/promtail/promtail.yaml -log.level debug
    networks:
      - loki

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=28jun2003
    depends_on:
      - loki
    networks:
      - loki

volumes:
  logs: