"""add title

Revision ID: 0790cc2a5483
Revises: a92e8a59f678
Create Date: 2024-06-07 12:43:37.548979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0790cc2a5483'
down_revision: Union[str, None] = 'a92e8a59f678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'title')
    # ### end Alembic commands ###
